# Generated by Django 2.1 on 2018-09-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.TextField()),
                ('date_valid', models.DateTimeField()),
                ('forecast_day', models.TextField()),
                ('PCWA', models.TextField()),
            ],
            options={
                'db_table': 'forecasts',
            },
        ),
    ]
